### ISSUE TITLE
Error in Planning module: 'BoxDetection' object has no attribute 'position'

### ISSUE THREAD

**Issue by srajangoyal** [avstack-lab/lib-avstack-api#4]
Hey guys, I'm getting this error in planning module.
Specifically, I've built a custom ego in Carla-sandbox, with `3dCamera` and `AdaptiveCruiseControl`.
I can provide more details in case you need it.

Could you please check?

Here is the back trace for your reference, if it helps:

WARNING:root:'BoxDetection' object has no attribute 'position'
Traceback (most recent call last):
  File "exec_standard.py", line 81, in main
    done = carla_manager.tick()
  File "/home/srajan/carla-sandbox/submodules/lib-avstack-api/avapi/carla/simulator/manager.py", line 88, in tick
    done = self.ego.tick(self.t_elapsed, self.frame, self.infrastructure)
  File "/home/srajan/carla-sandbox/submodules/lib-avstack-api/avapi/carla/simulator/ego.py", line 298, in tick
    ctrl = self.algorithms.tick(
  File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/ego/vehicle.py", line 37, in tick
    control = self._tick_modules(
  File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/ego/vehicle.py", line 193, in _tick_modules
    self.plan = self.planning(self.plan, self.environment, ego_state, dets_3d_cam, dets_2d, lanes)
  File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/planning/vehicle.py", line 131, in __call__
    obj_follow = components.get_object_to_follow(ego_state, objects_3d, lane_lines)         #### Hence, it works only for 3dObjects
  File "/home/srajan/carla-sandbox/submodules/lib-avstack-core/avstack/modules/planning/components.py", line 32, in get_object_to_follow
    obj.position
AttributeError: 'BoxDetection' object has no attribute 'position'
Done!
'''

**Comment by srajangoyal** [comment]
Apologies. I close it here and create a new one in avstack-core.
